---
title: "p8105_hw5_cj2493"
date: "November 6, 2018"
author: "Courtney Johnson"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
library(tidyverse)
library(purrr)
library(rvest)
library(httr)
```

## Problem 1

First, read in all the control arm files and experimental arm files. Then, tidy the data.

```{r, read_in, message = FALSE}
files_df = 
tibble(vec_files = list.files(path = "./data"), 
       vec_file_path = str_c("./data/", vec_files)) %>%
  mutate(observations = purrr::map(vec_file_path, read_csv)) %>%
  unnest() %>%
  janitor::clean_names() %>%
  separate(vec_files, into = c("arm", "subject"), sep = "_") %>%
  separate(subject, into = c("subject", "extension"), sep = "\\.") %>%
  select(-extension, -vec_file_path) %>%
  gather(key = week, value = measurement, week_1:week_8) %>%
  separate(week, into = c("word", "week"), sep = "_") %>%
  select(-word) %>%
  mutate(subject = as.factor(subject),
         arm = as.factor(arm),
         week = as.numeric(week)) 
```

Make a spaghetti plot showing observations on each subject over time, and comment on differences between groups.

```{r, spag_plot}
files_df %>%
  ggplot(aes(x = week, y = measurement, color = subject)) +
  geom_line() +
  facet_grid(~arm)
```


## Problem 2


```{r, read_api}
# city_homicides = GET("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv") %>%
  # content("parsed")

library(RCurl)

city_homicides = read_csv(getURL("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")) 

city_homicides = city_homicides %>%
  janitor::clean_names() %>%
  mutate(city_state = str_c(city, ", ", state)) 


```


```{r}
unsolved_summary = city_homicides %>%
  group_by(city_state) %>% 
  summarize(n = n(),
            sum_unsolved = sum(disposition == "Closed without arrest" | disposition == "Open/No arrest"))

baltimore_unsolved = unsolved_summary %>%
  filter(city_state == "Baltimore, MD")

prop_output = prop.test(baltimore_unsolved$sum_unsolved, baltimore_unsolved$n)
broom::tidy(prop_output)
baltimore_estimate = prop_output$estimate
baltimore_conf_int = prop_output$conf.int
```

Now do the same for all of the cities

```{r}

```

